### ISSUE TITLE
Feature: Submitting a Poll Response

### ISSUE THREAD

**Issue by alsona1188** [alsona1188/First-Agile-Project#3]
**User Story 1:**
_In order_ to provide my opinion  with regards to a certain running topics or event as a _user_, _I can_ select and submit an answer from the poll.

**User Story 2:**
_In order_ to provide anonymous feedback as a _user,_ _I can_ choose to hide my identity in the poll response. 

### Acceptance criteria:
- The option should be provided as a checkbox.
- The checkbox should be checked by default.
- The option should appear next to the submit button.
- After submitting the default submission confirmation should be adjusted to include the user name.

### Tasks:
- [ ] Update the view: the poll design (HTML and CSS) to include the checkbox and to show the name of the submitter
- [ ] Create a new field in the model to track the username.
- [ ] Update the controller function.
- [ ] Update unit tests scripts.
- [ ] Test the functionality

**User Story 3:**
_In order_ to provide additional thoughts beyond the response options as a _user_, _I can_ add a comment before I submit my poll response.
