### ISSUE TITLE
Feature: Publish a Poll

### ISSUE THREAD

**Issue by alsona1188** [alsona1188/First-Agile-Project#4]
**User Story 1:**
_In order_ to collect users feedback, as an _administrator_, _I can_ publish a poll. 

**User Story 2:**
_In order_ to automatically hide the poll as an _administrator_, _I can_ pick the expiry date while publishing the poll.

### Acceptance Criteria:
- The poll should disappear at 11:59 PM on the target date.
- The real estate of the poll should be reserved on the home page, a message that says "Stay tuned, a new poll is coming soon", should appear if no other poll is active.
- The administrator expiry date should be at least 3 days after the current date.

### Tasks:
- [ ] Update the admin module view: the poll design (HTML and CSS) to include date picker.
- [ ] Update the website view : show "Stay tunned, a new poll is coming soon."
- [ ] Create a JavaScript function to validate the expiry date is at least after 3 days.
- [ ] Create a job to check expired polls everyday at 11:59 PM and HIDE them.
- [ ] Update the controller function.
- [ ] Update unit test scripts
- [ ] Test the functionality
